#!/bin/bash
#
# $Id$
#


CLASSPATH="\
`dirname $0`/../share/java/synctimestamps-0.0.1-SNAPSHOT.jar:\
`dirname $0`/../share/synctimestamps/google-collections-1.0.jar:\
"
export CLASSPATH

tty=`tty 2>/dev/null`
returnValue=$?
if [ ${returnValue} -ne 0 ]
then
	exit ${returnValue}
else
	STTYARGS='-icanon min 1 time 0 -echo -icrnl intr undef flush undef start undef stop undef lnext undef susp undef quit undef'
	VMARGS="-client -Xmx6m -Dfile.encoding=`locale charmap` -Dterminal.debug=false"
	case `uname -s` in
	Linux)
		# Linux: stty doesn't accept any "dsusp" argument
		;;
	FreeBSD)
		# FreeBSD: dsusp defaults to ^Y
		STTYARGS="${STTYARGS} dsusp undef"
		;;
	SunOS)
		# Solaris: dsusp defaults to ^Y
		STTYARGS="${STTYARGS} dsusp undef"
		;;
	Darwin)
		# Mac OS X: dsusp defaults to ^Y
		STTYARGS="${STTYARGS} dsusp undef"
		# Mac OS X *does* have a 32-bit JVM
		VMARGS="${VMARGS} -d32"
		;;
	CYGWIN_NT-*)
		# CYGWIN: stty doesn't accept any "dsusp" argument
		;;
	*)
		;;
	esac
	stty ${STTYARGS}
	java ${VMARGS} com.google.code.synctimestamps.ui.terminal.InputDemo ${tty}
	returnValue=$?
	stty sane 2>/dev/null
	exit ${returnValue}
fi
