#!/bin/bash
#
# $Id$
#


CLASSPATH="\
`dirname $0`/../share/java/synctimestamps-0.0.1-SNAPSHOT.jar:\
`dirname $0`/../share/synctimestamps/google-collections-1.0.jar:\
"
export CLASSPATH

tty=`tty 2>/dev/null`
returnValue=$?
if [ ${returnValue} -ne 0 ]
then
	exit ${returnValue}
else
	stty -icanon min 1 time 0 -echo -icrnl intr undef flush undef start undef stop undef lnext undef dsusp undef susp undef quit undef
	java -client -d32 -Xmx6m -Dfile.encoding="`locale charmap`" -Dterminal.debug=false com.google.code.synctimestamps.ui.terminal.InputDemo ${tty}
	returnValue=$?
	stty sane 2>/dev/null
	exit ${returnValue}
fi
