#!/bin/bash
#
# $Id$
#

# "uname -o" is unavailable in OpenBSD and Solaris
case $(uname -s) in
	CYGWIN_NT-*)
		STS_HOME="$(cygpath -w "$(dirname $0)/..")"
		PATH_SEP=';'
		;;
	*)
		STS_HOME="$(dirname $0)/.."
		PATH_SEP=':'
		;;
esac

CLASSPATH="\
${STS_HOME}/etc/${project.artifactId}${PATH_SEP}\
${STS_HOME}/share/java/${project.artifactId}-${project.version}.jar${PATH_SEP}\
${STS_HOME}/share/synctimestamps/aopalliance-1.0.jar${PATH_SEP}\
${STS_HOME}/share/synctimestamps/commons-logging-1.1.1.jar${PATH_SEP}\
${STS_HOME}/share/synctimestamps/google-collections-${google.collections.version}.jar${PATH_SEP}\
${STS_HOME}/share/synctimestamps/log4j-${log4j.version}.jar${PATH_SEP}\
${STS_HOME}/share/synctimestamps/metadata-extractor-${metadata.extractor.version}.jar${PATH_SEP}\
${STS_HOME}/share/synctimestamps/sanselan-${sanselan.version}.jar${PATH_SEP}\
${STS_HOME}/share/synctimestamps/spring-aop-${spring.version}.jar${PATH_SEP}\
${STS_HOME}/share/synctimestamps/spring-asm-${spring.version}.jar${PATH_SEP}\
${STS_HOME}/share/synctimestamps/spring-beans-${spring.version}.jar${PATH_SEP}\
${STS_HOME}/share/synctimestamps/spring-context-${spring.version}.jar${PATH_SEP}\
${STS_HOME}/share/synctimestamps/spring-core-${spring.version}.jar${PATH_SEP}\
${STS_HOME}/share/synctimestamps/spring-expression-${spring.version}.jar${PATH_SEP}\
"

unset STS_HOME
unset PATH_SEP

export CLASSPATH

java com.google.code.synctimestamps.Main "$@"
returnCode=$?
exit ${returnCode}
