#!/bin/bash
#
# $Id$
#

CLASSPATH="\
`dirname $0`/../etc/${project.artifactId}:\
`dirname $0`/../share/java/${project.artifactId}-${project.version}.jar:\
`dirname $0`/../share/synctimestamps/aopalliance-1.0.jar:\
`dirname $0`/../share/synctimestamps/commons-logging-1.1.1.jar:\
`dirname $0`/../share/synctimestamps/google-collections-${google.collections.version}.jar:\
`dirname $0`/../share/synctimestamps/log4j-${log4j.version}.jar:\
`dirname $0`/../share/synctimestamps/metadata-extractor-${metadata.extractor.version}.jar:\
`dirname $0`/../share/synctimestamps/sanselan-${sanselan.version}.jar:\
`dirname $0`/../share/synctimestamps/slf4j-api-${slf4j.version}.jar:\
`dirname $0`/../share/synctimestamps/slf4j-log4j12-${slf4j.version}.jar:\
`dirname $0`/../share/synctimestamps/spring-aop-${spring.version}.jar:\
`dirname $0`/../share/synctimestamps/spring-asm-${spring.version}.jar:\
`dirname $0`/../share/synctimestamps/spring-beans-${spring.version}.jar:\
`dirname $0`/../share/synctimestamps/spring-context-${spring.version}.jar:\
`dirname $0`/../share/synctimestamps/spring-core-${spring.version}.jar:\
`dirname $0`/../share/synctimestamps/spring-expression-${spring.version}.jar:\
"
export CLASSPATH

java com.google.code.synctimestamps.Main "$@"
returnCode=$?
exit ${returnCode}
